
    <div id="content">

		<h2 class="title-content"><?php echo $this->titulo; ?></h2>
		
		<ol>
			<li>Perguntas Frequentes</li>
				<ol>
					<li>O que &eacute; a Compra na Cidade?</li>
					<p>A Compranacidade é um site de compras coletivas do Brasil. Acesse a ofertas incríveis para você aproveitar os melhores  lugares da sua cidade. São descontos de 50% a 80% em restaurantes, spas, teatros e muito mais na sua caixa de e-mail, diariamente.
					Para que você possa aproveitar essas ofertas, um número mínimo de compradores precisa ser atingido. Nós conseguimos os descontos, você convida os seus amigos para aproveitarem também, e juntos aprveitamos o que tem de melhor na sua cidade!</p>
					
					<li>Como funciona?</li>
					<p>Selecionamos o que há de melhor na cidade e publicamos com um super desconto por um período específico no nosso site. A oferta também é enviada por e-mail para todos que se cadastram no Compranacidade.
					Quem gosta da oferta, compra e aguarda a confirmação do pagamento do PagSeguro. Se a compra for aprovada, é hora de esperar o cupom do Compranacidade, que será enviado em até 24 horas após o encerramento da oferta. O cupom também será disponibilizado para visualização e impressão.
					Para utilizar o cupom, fique atento à data de início da validade do mesmo. Feito isso, apresente o código do cupom e usufrua de um serviço super bacana.</p>
					
					<li>A CompraNaCidade  é um site seguro?</li>
					<p>A Compra na Cidade  é um site extremamente seguro. Utilizamos a plataforma de pagamentos do PagSeguro, que garante total segurança e sigilo dos dados transmitidos.</p>
					
					<li>O que eu faço para ficar por dentro das Ofertas?</li>
					<p>Basta cadastrar o seu e-mail na CompraNaCidade e se juntar ao outros usuarios. Assim, as ofertas serão entregues fresquinhas, diariamente, na sua caixa de e-mail.
					Para se cadastre  em "Receba E-mail diário"</p>
					
					<li>Eu gostei da oferta de hoje. O que eu faço agora?</li>
					<p>É só clicar em "COMPRAR" antes da promoção terminar. Seja rápido, pois todas as ofertas ficam por apenas pouco tempo no ar e, algumas delas, tem limite e podem esgotar antes do tempo previsto acabar.
					Para finalizar a compra, você precisará colocar o nome da pessoa que utilizará o cupom e estar logado na sua conta Compranacidade (é imprescindível estar logado).Você, então, será direcionado ao site do PagSeguro para efetuar o pagamento.
					Se o número mínimo de compradores for atingido, é só esperar a oferta ser encerrada. Você receberá o CUPOM com o seu CÓDIGO no seu e-mail em até 24h após a oferta ser encerrada. Se por algum motivo você não receber, acesse a sua conta. O cupom também estará disponível lá depois do mesmo prazo.</p>
					
					<li>E se o número mínimo não for atingido?</li>
					<p>Caso o número mínimo de compradores para a oferta que você comprou não seja atingido, você será comunicado por e-mail que a sua compra foi cancelada, e que o valor total pago foi devolvido. O nosso sistema de pagamentos é integrado ao PagSeguro, que garante a compra com segurança e a devolução do valor no caso de não fechamento do grupo mínimo de compradores.
					Se você não quiser perder esta oferta, convide rápido os seus amigos para comprá-la também, e garanta logo o seu super desconto! Quanto mais pessoas souberem do que está rolando na Compranacidade , mais chances para ativar a oferta.</p>
					
					<li>O que devo fazer se não estiver recebendo os emails da Compranacidade?</li>
					<p>O primeiro passo é verificar a sua caixa de SPAM e adicionar o e-mail sac@compranacidade.com.br à sua lista de e-mails seguros. Se ainda assim você não receber os e-mails da Compranacidade ou entre em contato conosco através do e-mail sac@compranacidade.com.br</p>
					
				</ol>
			<li>Dúvidas sobre o Login minha conta</li>
				<ol>
					<li>Como faço para fazer o login na minha conta?</li>
					<p>Depois de clicar em log in na página principal, você será direcionado à página onde deverá inserir o seu e-mail e senha nos campos apropriados. Uma vez logado você poderá comprar a Oferta do Dia, acessar seus cupons, visualizar créditos, acessar o seu link único para convidar amigos, editar preferência de e-mail e alterar senha.</p>
					
					<li>Esqueci minha senha! Como faço para recuperá-la?</li>
					<p>Entre no site de Compranacidade, clique em log in. Na página do log in, clique na última frase: "Esqueceu senha?". Você será direcionado à página "Lembrar Senha", onde deverá preencher o campo com o e-mail que você cadastrou na compranacidade. Após clicar em "Enviar", uma nova senha será enviada para o seu e-mail cadastrado.</p>
				</ol>
			
			<li>Dúvidas sobre o Cupom</li>
				<ol>
					<li>Como faço para acessar meus Cupons?</li>
					<p>Em até 24h após o encerramento da oferta, seu Cupom será enviado para o seu email e será disponibilizado para visualização e impressão na sua conta.
					Para visualizar seu Cupom, clique em Conta e Cupons. Você visualizará o histórico e o status das suas compras. Você deverá clicar em "Cupom Disponível" para visualizar e/ou imprimir seus Cupons.</p>
					
					<li>Não consigo visualizar meus Cupons. Qual o problema?</li>
					<p>Em alguns casos, os usuários tem mais de um cadastro no Compra na Cidade. Por favor, verifique o e-mail como qual você efetuou a sua compra, pois o seu cupom estará disponível nessa conta em até 24h após a oferta se encerrar.
					Se isso foi feito e você ainda assim não consegue visualizar o seu Cupom, envie o seu comprovante de pagamento do PagSeguro para sac@compranacidade.com.br, para análise.</p>
					
					<li>Como faço para utilizar o Cupom?</li>
					<p>Para utilizar seu Cupom, você tem a opção de apresentar a versão impressa ou somente o código diretamente no estabelecimento, observando todos os regulamentos, incluindo o prazo de validade para o uso do cupom.</p>
					
					<li>Como altero o nome no Cupom?</li>
					<p>Se você desejar alterar o nome da pessoa que vai usar o cupom, clique em conta -> cupons -> cupom disponível-> alterar nome</p>
					
					<li>Comprei mais de um Cupom, mas só recebi um. O que faço para ter acesso ao(s) outro(s)?</li>
					<p>O seu provedor pode identificado o(s) e-mail(s) como spam. Nesse caso, sugerimos verificar sua caixa de spam e/ou visualizar os cupons faltantes diretamente na sua conta Compranacidade.</p>
										
				</ol>
			
			<li>Dúvidas com o Pagamento e com o PagSeguro</li>
				<ol>
					<li>Porque minha compra foi cancelada no Pagseguro?</li>
					<p>O sistema de pagamentos do Pagseguro é independente da compranacidade. Não temos acesso a esse sistema. Por favor, para esclarecimentos entre em contato diretamente com o SAC do PagSeguro XX-11-5627-3440</p>
					
					<li>Efetuei minha compra, mas não recebi nenhum comprovante. E agora?</li>
					<p>Aguarde o comprovante de pagamento que será enviado pelo PagSeguro. Pode ser que ele demore um pouco mais. Se o comprovante não chegar, verifique se você tem mais de um e-mail de cadastro na Compranacidade, Ligue para o SAC do Pagseguro para ver o status de pagamento XX-11 5627-3440</p>
				
					<li>Minha compra foi cancelada e acabei efetuando duas compras! Como estorno uma?</li>
					<p>Podemos estornar ou transformar em créditos Compranacidade o valor da sua compra. Envie o seu comprovante de pagamento do PagSeguro para o nosso SAC para efetuarmos o estorno, ou se você preferir, transformarmos o valor em Crédito Compranacidade para que você possa utilizar na sua próxima compra.</p>
					
					<li>Eu preciso usar o desconto no mesmo dia em que eu comprei?</li>
					<p>Não. Todos os descontos tem data de validade, que variam para cada oferta e estão no regulamento da Oferta do Dia, na página de Ofertas. Os descontos devem ser usados dentro da data de validade, mas esta data nunca será a mesma data da compra.</p>
					
					<li>O que faço para me tornar um Parceiro da Compranacidade?</li>
					<p>Primeiramente, obrigada pelo interesse na Compranacidade!   Acesse a pagina seja parceiro e entre em contato conosco. Quanto mais detalhada for a descrição do seu serviço e/ou produto melhor.</p>
					
					<li>Quando a Compranacidade vai chegar na minha cidade?</li>
					<p>Logo! Enquanto não chegamos aí, sinta-se à vontade para indicar Parcerias que podemos fechar na sua cidade e cidades onde devemos chegar através do nosso formulário</p>
				
					<li>Comunique qualquer imprevisto com o Parceiro</li>
					<p>A Compranacidade  se orgulha em oferecer somente as melhores ofertas aos Usuarios. Quando somos alertados de alguma situação inesperada com algum de nosso Parceiro, entramos em contato imediatamente com ele para encontrar a melhor solução. Por isso, por favor, comunique qualquer imprevisto ou sugestão através de nosso SAC.</p>
		
				</ol>
		</ol>

	</div>