
    <div id="content">

		<h2 class="title-content"><?php echo $this->titulo; ?></h2>

		<div class="categorias-meus_cupons">
			<strong>Categorias:</strong>
			<a href="/conta/meus-cupons/">Concretizados</a> | 
			<a href="/conta/meus-cupons/naoconcretizados">N&atilde;o Concretizados</a>
		</div>
		
		<h2 class="meus_cupons">N&atilde;o Concretizados</h2>
		
		<table class="DataTable" id="cupons-table">
			<thead>
				<tr>
					<th class="item item-email">T&iacute;tulo</th>
					<th class="item item-cidade" width="150">Status</th>
				</tr>
			</thead>
			<tbody>
	<?php
		foreach ( $this->cupons as $value ){
	?>
			<tr class="item item">
				<td class="data" valign="middle"><?php echo strip_tags($value['titulo']); ?></td>
				<td class="data" align="center">A oferta n&atilde;o foi ativada.</td>
			</tr>
	<?php
		}
	?>
		</tbody>
		</table>

	</div>
