
    <div id="content">

		<h2 class="title-content"><?php echo $this->titulo; ?></h2>
		
		<p><strong>Compra na Cidade &eacute; o primeiro site brasileiro de compra coletiva solidaria.</strong></p><br/>
		
		<p>A partir da venda de todos os produtos e servi&ccedil;os que ofertamos, destinamos 5% do valor desta venda a projetos solid&aacute;rios.</p><br/> 
		
		<p>Sem doa&ccedil;&otilde;es monet&aacute;rias e sim concretas, pretendemos tornar a troca mercadol&oacute;gica de produtos e servi&ccedil;os em a&ccedil;&otilde;es reais de ajuda em uma atitude de caridade efetiva; buscamos projetos concretos onde realmente as pessoas menos favorecidas sejam beneficiadas.</p><br/><br/>
		
		<p><strong>Compra coletiva: o assunto do momento no Brasil</strong></p><br/>
		
		<p>O Compra na Cidade consegue negociar descontos exclusivos de at&eacute; 80% garantindo mais clientes aos comerciantes e pre&ccedil;os atraentes aos consumidores.</p><br/>
		
		<p>Os usu&aacute;rios cadastrados no site recebem alertas por email com informa&ccedil;&otilde;es sobre as ofertas di&aacute;rias por cidade.</p><br/>
		
		<p>O Compra na Cidade est&aacute; dispon&iacute;vel para os moradores da cidade de Natal, Fortaleza, Recife, Jo&atilde;o Pessoa e Campina Grande e em junho estar&aacute; tamb&eacute;m nas principais capitais do pa&iacute;s, incluindo S&atilde;o Paulo, Rio de Janeiro, Belo Horizonte, Porto Alegre, Salvador, Bras&iacute;lia e Curitiba.</p><br/>
		
		<p>Comprar no site Compra na Cidade significa ter acesso a grandes descontos em produtos e servi&ccedil;os de primeira qualidade contribuindo de maneira direta com uma causa social.</p><br/>
		
		<p>Para que a super oferta seja efetivada, antes que o tempo acabe todos os interessados podem chamar ou avisar seus amigos e conhecidos em suas redes de relacionamento, email, Facebook, Orkut ou Twitter. Assim, al&eacute;m de viabilizar nossa super oferta, voc&ecirc; participa paralelamente de uma a&ccedil;&atilde;o concreta de solidariedade.</p><br/><br/>
		
		<p><strong>Uma maneira de comprar e ajudar ao mesmo tempo</strong></p><br/>
		
		<p>Nossa filosofia de trabalho &eacute; desenvolver uma oferta de produtos, servi&ccedil;os e experi&ecirc;ncias que, alem de ser atrativos pelo bom pre&ccedil;o, permite ao comprador contribuir com os fins sociais descritos no anuncio.</p><br/><br/>
		
		<p><strong>Uma comunidade solidaria em Internet</strong></p><br/>
		
		<p>Queremos tornar a comunidade da Internet, um f&oacute;rum de participa&ccedil;&atilde;o mais solid&aacute;rio.</p>

	</div>