<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8859-1" />
		<title>Compra na Cidade</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('public/css/images/favicon.ico'); ?>" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/style.css'); ?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/style.css'); ?>" type="text/css" />

		<script src="<?php echo $this->baseUrl('public/js/cufon-yui.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('public/js/quicksand.font.js'); ?>" type="text/javascript"></script> 
        <script type="text/javascript">
			Cufon.replace('.title-content', { fontFamily: 'Quicksand Bold Regular', hover: true }); 
		</script>
	</head>

<body style="background: #FFFFFF url('<?php echo $this->baseUrl('public/css/images/bkg.jpg'); ?>') repeat-x scroll 0px 155px;">

	<div id="header" style="height: 143px !important;">
		<div class="header-content" style="height: 155px;">
		
			<div class="logo">
				<img src="<?php echo $this->baseUrl('public/css/images/logo.png'); ?>" />
			</div>
			
		</div>
	</div>

    <div id="content" style="min-height:200px;">

		<h2 class="title-content">Compra confirmada!</h2>

		<p>Agradecemos pela escolha da sua compra conosco.<br/>
		
	</div>


</body>
</html>