    <div id="content">

		<h2 class="title-content"><?php echo $this->titulo; ?></h2>
		
		<img src="<?php echo $this->baseUrl('/uploads/'.str_replace( ',', '', $this->oferta['imagem_cupom'] )); ?>" class="foto_oferta-comprada" width="195" height="125" />
		
		<div class="espaco_form-compra">
		
			<h2><?php echo strip_tags($this->oferta['titulo']); ?></h2>

			<form action="" method="post">
				<div class="compra-content">
				
						<table class="table1">
							<tr>
								<td align="center" class="text-header">Quantidade</td>
								<td width="15"></td>
								<td align="center" class="text-header">Valor &Uacute;nico</td>
								<td width="15"></td>
								<td align="center" class="text-header">Total</td>
							</tr>
							<tr>
								<td align="center" class="text">
									<?php
										if($this->oferta['cupons_por_pessoa'] >= 1):
									?>
										<select id="numero_utilizadores" name="quantidade">
									<?php
											$cupons = $this->oferta['cupons_por_pessoa'] - $this->qtd_cupom;
											for($i=1; $cupons >= $i; $i++):
									?>
										<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
									<?php
											endfor;
									?>
										</select>
									<?php
										else:
									?>
											<font style="font-size: 20px;" class="text-quantidade">1</font></td>									
									<?php
										endif;
									?>
								</td>
								<td align="center" class="espaco">x</td>
								<td align="center" class="text">
									<font style="font-size: 12px;">R$</font>
									<font style="font-size: 20px;" class="text-preco"><?php echo Model_Util::stringToMoney( $this->oferta['M_preco_oferta'] ); ?></font></td>
								<td align="center" class="espaco">=</td>
								<td align="center" class="text">
									<font style="font-size: 12px;">R$</font>
									<font style="font-size: 20px;" class="text-total"><?php echo Model_Util::stringToMoney( $this->oferta['M_preco_oferta'] ); ?></font>
								</td>
							</tr>
						</table>			
				
						<div class="espaco-utilizadores">
							
							<strong style="padding: 5px; font-size: 15px;">Apenas campos preenchidos ser&atilde;o considerados:</strong>
							
							<table cellspacing="5" class="utilizadores">
							</table>
						</div>
				
						<?php
							if($this->oferta['cupons_por_pessoa'] == 0):
						?>
								<a class="add"><img src="<?php echo $this->baseUrl('public/css/images/add.gif'); ?>" class="left" /> &nbsp;Mais</a>
						<?php
							endif;
						?>
				
				</div>
				<div class="linha-cima"></div>
				<div class="linha-baixo"></div>
				<div class="compra-footer">
					<font class="text-valor_total">Valor Total:</font>
					<small class="text-cifrao">R$</small>
					<font class="text-preco"><?php echo Model_Util::stringToMoney( $this->oferta['M_preco_oferta'] ); ?></font>
				</div>
	
				<p align="right" style="font-size: 16px; font-weight: bold; text-align:right;"><br/><br/>Desbloqueie o popup do seu<br/>browser para efetuar uma compra!</p>
	
				<div style="margin: 0px auto; text-align: right; margin-top: 20px; margin-bottom: 20px;">
					<button class="Enviar ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" type="submit" id="Logar" name="Logar" role="button" aria-disabled="false">
						<span class="ui-button-text">Finalizar Compra</span>
					</button>
				</div>
			
				<input type="hidden" name="quantidade" value="1" />
				<input type="hidden" name="preco" value="<?php echo str_replace( '.', '', $this->oferta['M_preco_oferta'] ); ?>" />
				<input type="hidden" name="descricao" value="<?php echo utf8_decode(strip_tags($this->oferta['titulo'])); ?>" />
			
			</form>

		</div>
	</div>