
    <div id="content">

		<h2 class="title-content"><?php echo $this->titulo; ?></h2>


			<?php
				foreach($this->paginator as $record): 
					
					$economia = $record['M_preco_normal'] - $record['M_preco_oferta'];
					
					$titulo = (strlen(strip_tags($record['titulo'])) > 153) ? substr(strip_tags($record['titulo']), 0, 153)."..." : strip_tags($record['titulo']) ;
					
			?>
            <div class="round-oferta" style="height:auto;">
            	<p><?php echo date('d/m/Y',$record['D_data_inicio']); ?></p>
            	<h2><a href="/<?php echo $this->cidade; ?>/oferta/<?php echo $record['id']; ?>"><?php echo $titulo; ?></a></h2>
            	
            	<a href="/<?php echo $this->cidade; ?>/oferta/<?php echo $record['id']; ?>"><img src="<?php echo $this->baseUrl('/uploads/'.str_replace( ',', '', $record['imagem_cupom'] )); ?>" width="195" height="125" /></a>
            	
            	<div class="caixa-preco">
            		<p class="content">
            			<font class="vendidos">Vendidos: <?php echo $record['numero_atual_compradores']; ?></font><br/><br/>
            			<font class="precos">
            				Pre&ccedil;o Normal: R$ <?php echo Model_Util::stringToMoney( $record['M_preco_normal'] ); ?><br/>
            				Economia: R$ <?php echo Model_Util::stringToMoney( $economia ); ?>
            			</font>
            		</p>
            		<div class="preco-oferta">Pre&ccedil;o: R$ <?php echo Model_Util::stringToMoney( $record['M_preco_oferta'] ); ?></div>
            	</div>
            	
            </div>
            <?php 
            	endforeach;
            ?>

			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

	</div>