<?php $oferta = $this->ofertaDia; ?>
<?php $parceiro = $this->parceiro; ?>

    <div id="content">

    	<div class="col left margin-right">
            <div class="round-info">
				<div class="roundtop">
					<img src="<?php echo $this->baseUrl('public/css/images/top-left.gif'); ?>" alt="" width="15" height="15" class="corner" style="display: none" />
				</div>
                
                <div class="content-info_oferta">
                
                	<div class="seta"></div>
                
                	<div class="preco-de preco-de-frente">de R$<?php echo  $oferta['M_preco_normal']; ?></div>
                	<div class="preco-de preco-de-tras">de R$<?php echo  $oferta['M_preco_normal']; ?></div>
                    
                	<div class="preco-por preco-por-frente">por R$<?php echo  $oferta['M_preco_oferta']; ?></div>
                	<div class="preco-por preco-por-tras">por R$<?php echo  $oferta['M_preco_oferta']; ?></div>
                    

					<div class="info">
					
						<?php
							if($oferta['D_data_fim'] > time()):
						?>
					
							<?php
								$link = (!Model_Access::isGuest() && !Model_Modelo::isAdmin()) ? 'href="/compra/'.base64_encode( base64_encode( $oferta['id'] ) ).'"' : 'href="#" onclick="javascript:comprar();"' ;
							?>
						
	                    	<a <?php echo $link; ?>>
	                    		<img src="<?php echo $this->baseUrl('public/css/images/bt_comprar.png'); ?>" />
	                    	</a>
	                    	
							<a <?php echo $link; ?>>
								<img src="<?php echo $this->baseUrl('public/css/images/bt_compre_amigo.png'); ?>" />
							</a>
						
						<?php
							else:
						?>
                        	<img src="<?php echo $this->baseUrl('public/css/images/bt_encerrado.gif'); ?>" class="encerrado" />
                        <?php
                        	endif;
                        ?>
                        
	                    <div class="divisoria"></div>
                        
                        <div class="espaco-contador">
	                        <div class="contador" id="relogioh"><?php echo  $oferta['horas']; ?></div>
	                        <div class="contador-pontos">:</div>
	                        <div class="contador" id="relogiom"><?php echo  $oferta['minutos']; ?></div>
	                        <div class="contador-pontos">:</div>
	                        <div class="contador" id="relogios"><?php echo  $oferta['segundos']; ?></div>
                        </div>
                        
						<?php
							$hora = date('H', $oferta['D_data_fim']);
							$minuto = date('i', $oferta['D_data_fim']);
							$segundo = date('s', $oferta['D_data_fim']);
							
							$ano = date('Y', $oferta['D_data_fim']);
							$mes = date('m', $oferta['D_data_fim']);
							$dia = date('d', $oferta['D_data_fim']);
													
							$tempoRestante = mktime($hora,$minuto,$segundo,$mes,$dia,$ano) - time();
						?>
                        
						<script type="text/javascript">
                        $(function(){
                            $('.espaco-contador').each(function(){
                                  var relogio = $(this);

                                  var now = '<?php echo  date( 'Y,m,d,H,i,s', time() ); ?>';
                                  var timenow = now.split(',');

                                  var timeleft = '<?php echo  date( 'Y,m,d,H,i,s', $oferta['D_data_fim'] ); ?>';
                                  var time = timeleft.split(',');
                                  var data_final = new Date(time[0], time[1], time[2], time[3], time[4], time[5]);
                                  var data_atual = new Date(timenow[0], timenow[1], timenow[2], timenow[3], timenow[4], timenow[5]);

                                  relogio.countdown({
                                        until: data_final,
                                        timezone: -3,
                                        format: 'HMS',
                                        serverSync: function(){
                                              return data_atual
                                        },
                                        layout:
                	                        '<div class="contador" id="relogioh">{hn}</div>'
                	                        +'<div class="contador-pontos">:</div>'
                	                        +'<div class="contador" id="relogiom">{m10}{m1}</div>'
                	                        +'<div class="contador-pontos">:</div>'
                	                        +'<div class="contador" id="relogios">{s10}{s1}</div>',
                                        timeSeparator: '',
                                        expiryText: 'O tempo acabou',
                                        onExpiry: function() {
                                              //relogio.siblings('div.comprar,div.presentear,div.lance').fadeOut(800);
                                        }
                                  });
                            });
                      });
						</script>
                        
                        <?php
                        	$txtvendidos = (($this->vendido == 0) || ($this->vendido == 1)) ? $this->vendido.' vendido' : $this->vendido . ' vendidos' ;
                        ?>
                        
                        <p class="vendidos"><?php echo $txtvendidos; ?></p>
                        
						<?php if ( $oferta['numero_atual_compradores'] >= $oferta['minimo_compradores']) : ?>
                        	<img src="<?php echo $this->baseUrl('public/css/images/compra_ativada.png'); ?>" />
							<p class="minimo">M&iacute;nimo de <?php echo $oferta['minimo_compradores']; ?> atingido</p>
						<?php endif; ?>
                        
                    </div>
                    
                </div>
                
				<div class="roundbottom">
					<img src="<?php echo $this->baseUrl('public/css/images/bottom-left.gif'); ?>" alt="" width="15" height="15" class="corner" style="display: none" />
				</div>
            </div>
            
            <div class="banner">
            	<a href="#"><img src="<?php echo $this->baseUrl('public/css/images/banner_projeto.gif'); ?>" /></a>
			</div>
            
            <div class="banner anunciante">
            	<a href="#"><img src="<?php echo $this->baseUrl('public/css/images/banner_anunciante.gif'); ?>" /></a>
			</div>
            
            <div class="banner anunciante">
            	<a href="http://www.multclick.com.br" target="_blank"><img src="<?php echo $this->baseUrl('public/css/images/banner_anunciante2.gif'); ?>" /></a>
			</div>
            
        </div>
        
    	<div class="col-content left">
        	<div class="compartilhe" style="margin-bottom: 20px;">
            	<font class="tit-compartilhe left">Compartilhe com os amigos:</font>
                <div class="left">
                	<ul>
						<li class="compartilhe-facebook"><font><a target="_blank" href="http://www.facebook.com/share.php?u=<?php echo "http://compranacidade.com.br/".$this->cidade."/oferta/".$oferta['id']."&t=".strip_tags($oferta['titulo']); ?>" style="color: #4c6b99;">facebook</a></font></li> 
						<li class="compartilhe-twitter"><font><a target="_blank" href="http://twitter.com/home?status=<?php echo "http://migre.me/compartilhar?url=(".urlencode(strip_tags($oferta['titulo']) . " || http://compranacidade.com.br/". $this->cidade."/oferta/".$oferta['id']); ?>" style="color: #65d4f6;">twitter</a></font></li>
						<li class="compartilhe-orkut"><font><a target="_blank" href="http://promote.orkut.com/preview?nt=orkut.com&tt=<?php echo strip_tags($oferta['titulo'])."&du=http://compranacidade.com.br/".$this->cidade."/oferta/".$oferta['id'];?>" style="color: #bb2192;">orkut</a></font></li> 
						<li class="compartilhe-email"><font><a href="#" style="color: #787676;">e-mail</a></font></li>
                    </ul>
                </div>
            </div>

            	<?php
            		$titulo = str_replace(array('<p>','</p>'), "", $oferta['titulo'] );
            	?>
            	  <font class="titulo-frente" color="#<?php echo $oferta['cortitulo']; ?>"><?php echo $titulo; ?></font>
            
            <div class="oferta">
            
				<?php
					if(count($oferta['imagens'])-1 > 1):
				?>
            	
				        <div class="main_view">
				
				            <div class="window">	
				                <div class="image_reel">
				                	<?php
				                		foreach($oferta['imagens'] as $foto):
				                			if($foto != ""):
				                	?>
				                    	<img src="<?php echo $this->baseUrl('/uploads/'.$foto); ?>" alt="" />
				                    <?php
				                    		endif;
				                    	endforeach;
				                    ?>
				                </div>
				            </div>
				            <div class="paging">
				            	<?php
				            		for($i = 1; count($oferta['imagens']) > $i; $i++ ){
				            	?>
				                		<a href="#" rel="<?php echo $i; ?>"><?php echo $i; ?></a>
				                <?php
				            		}
				                ?>
				            </div>
				        </div>
				        
		        <?php
		        	else:
		        ?>
		        
						<img src="<?php echo $this->baseUrl('/uploads/'.$oferta['imagens'][0]); ?>" alt="" />
		        
		        <?php
					endif;
		        ?>
            </div>

			<ul id="abas">
            	<li><a class="aba-destaque" href="#tab1"></a></li>
                <li><a class="aba-regras" href="#tab2"></a></li>
                <li><a class="aba-empresa" href="#tab3"></a></li>
                <li><a class="aba-vote" href="#tab4"></a></li>
			</ul>
            
            <div id="tab1" class="tab-content">
            	<a name="tab1" /></a>
            		
            		<?php
            			if($oferta['video']):
            				$link = explode('&',$oferta['video']);
							$link = explode('v=',$link[0]);
            		?>
						<div class="video"><iframe title="YouTube video player" width="390" height="323" src="http://www.youtube.com/embed/<?php echo $link[1]; ?>?rel=0" frameborder="0" allowfullscreen></iframe></div>
            		<?php endif;?>
            		
            		<?php echo  nl2br( $oferta['destaques'] ); ?>
            		
            </div>
            
            <div id="tab2" class="tab-content">
            	<a name="tab2" /></a>
            	
            		<?php echo  nl2br( $oferta['regras'] ); ?>
            		
            </div>
            
            <div id="tab3" class="tab-content">
            	<a name="tab3" /></a>
            	
					<h2><?php echo $parceiro['nome']; ?></h2>

					<?php if(!empty($parceiro['logo'])): ?>
						<img style="float:right; margin: 10px;" src="<?php echo '/uploads/'.str_replace( ',', '', $parceiro['logo'] ); ?>" />
					<?php endif; ?>
					
					<p>
						<?php echo  $parceiro['sobre']; ?>
					</p>
					
					<br/>
					
					<p>
						<span><?php echo  $parceiro['rua']; ?>, <?php echo  $parceiro['numero']; ?><br/>
						
						<?php echo  $parceiro['bairro']; ?> - <?php echo  $parceiro['cep']; ?><br/>
						
						Tel: <?php echo  $parceiro['telefone']; ?> <?php if($parceiro['celular']) echo $parceiro['celular']; ?><br/>
						
						E-mail: <a href="mailto:<?php echo  $parceiro['email']; ?>"><?php echo  $parceiro['email']; ?></a><br/>
						
						Website: <a href="http://<?php echo  $parceiro['site']; ?>"><?php echo  $parceiro['site']; ?></a>
						
						</span><br/><br/>
						
						<div id="googlemaps" style="width: 408px; height: 187px;"></div>
					</p>
            		
            </div>
            
            <div id="tab4" class="tab-content">
            	<a name="tab4" /></a>
            		
            </div>

            
        </div>
        
    	<div class="col right margin-left">
            <div class="round-outras_fertas">
				<div class="roundtop">
					<img src="<?php echo $this->baseUrl('public/css/images/top-left.gif'); ?>" alt="" width="15" height="15" class="corner" style="display: none" />
				</div>
                
                <div class="content-outras_ofertas">
                
                	<h2 class="tit-outras_ofertas">Outras compras</h2>
                    
                    <?php
                    	$i = 0;
                    	foreach($this->ofertasBonus as $outrasOfertas):
                    ?>                  
	                	<div>
	                    	<a href="/<?php echo $this->cidade; ?>/oferta/<?php echo $outrasOfertas['id']; ?>"><img src="<?php echo $this->baseUrl('/uploads/'.str_replace( ',', '', $outrasOfertas['imagem_cupom'] )); ?>" class="foto-oferta" /></a>
	                        <p align="left"><strong><?php echo $outrasOfertas['titulo']; ?></strong></p>
	                        
	                        <div class="botoes">
	                            <font class="left">R$ <?php echo Model_Util::stringToMoney( $outrasOfertas['M_preco_oferta'] ); ?></font>
	                            <a href="/<?php echo $this->cidade; ?>/oferta/<?php echo $outrasOfertas['id']; ?>" class="left"></a>
	                        </div>
	                    </div>
	                    
					<?php
						if($i != 2):
					?>
	                    	<div class="line"></div>
	                <?php 
	                	endif;
	                	
	                	$i++;
	                	
	                	endforeach;
	                ?>
                    
                </div>
                
				<div class="roundbottom">
					<img src="<?php echo $this->baseUrl('public/css/images/bottom-left.gif'); ?>" alt="" width="15" height="15" class="corner" style="display: none" />
				</div>
            </div>
        </div>
    </div>
    
<?php if(Model_Access::isGuest() && !Model_Modelo::isAdmin()): ?>    
	<script type="text/javascript">
		function comprar(){
			$(function(){
                $( '#dialog' ).html('Logue-se ou se cadastre no Site para efetuar a compra!');
                $( '#dialog' ).dialog({
                	title: 'Erro',
                	resizable: false,
                	height: 130,
                	modal: true,
                	buttons: {
						Ok: function() {
							$( this ).dialog( 'close' );
            			}
        			}
    			});
			});
		}
	</script>
<?php endif; ?>
    
		<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAPxyatMsc6KsS5Ro2AbIyABTaXe-9_UJ8CfnNqfHZvyCg5dKn2xRNb7my4_5SywKgmRnE42mm64lrpA" type="text/javascript"></script>
		<script type="text/javascript">
	        if (GBrowserIsCompatible()) {
	          var map = new GMap2(document.getElementById("googlemaps"));

	          var localizacao = '<?php echo  $parceiro['rua']; ?> <?php echo  $parceiro['numero']; ?> <?php echo  $parceiro['bairro']; ?>';
	          
	          var geocoder = new GClientGeocoder();
				if (geocoder) {
					geocoder.getLatLng(
					localizacao,
					function(point) {
						if (!point) {
							Boxy.alert(localizacao + " not found");
							} else {
								map.setCenter(point, 13);
								var marker = new GMarker(point);
								map.addOverlay(marker);
								marker.openInfoWindowHtml(localizacao);
							}
						}
					);
				}
	        }
		</script>