    <div id="content">

		<h2 class="title-content"><?php echo $this->titulo; ?></h2>
		
		<p>Junte-se a uma equipe jovem, vencedora e com muita vontade de crescer.</p><br/>
		
		<p>Estamos nos expandindo rapidamente em todo o pa&iacute;s. Se voc&ecirc; deseja contribuir com o nosso time, contate-nos atrav&eacute;s do email: <a href="mailto:carreiras@compranacidade.com.br">carreiras@compranacidade.com.br</a>.</p><br/>
		
		<p>Especifique a &aacute;rea de interesse e envie seu CV e uma carta explicando porque voc&ecirc; &eacute; a pessoa certa para fazer parte do nosso time.</p><br/><br/>
		
		<p><strong>Estamos selecionando Representantes de Vendas em todos os estados do Brasil</strong></p><br/>
		
		<p><strong>Requisitos e experi&ecirc;ncias necess&aacute;rias:</strong></p><br/>
		<ul style="margin-left: 14px;">
			<li>Veiculo pr&oacute;prio</li>
			<li>Notebook com acesso a Internet;</li>
			<li>Superior Completo preferencialmente;</li>
			<li>Experi&ecirc;ncia com vendas externas;</li>
			<li>Com bom relacionamento social na cidade local;</li>
			<li>&Oacute;tima habilidade interpessoal, boa postura e educa&ccedil;&atilde;o, bom ouvinte, trabalhe bem sob press&atilde;o;</li>
		</ul><br/><br/>
		
		<p><strong>Responsabilidades:</strong></p><br/>
		<ul style="margin-left: 14px;">
			<li>Identificar prospectos ideais para parcerias, recomendando os melhores estabelecimentos de sua cidade;</li>
			<li>Desenvolver estrat&eacute;gia de vendas baseada em pesquisas de mercado;</li>
			<li>Conduzir campanhas de vendas;</li>
		</ul><br/><br/>
		
		<p>Criar parcerias que beneficiem ambos os parceiros, negociando diversas vari&aacute;veis da oferta.</p><br/>

	</div>