
<div id="content">

<h2 class="title-content"><?php echo $this->titulo; ?></h2>

<p><strong>Vantagens de anunciar na Compra na Cidade</strong></p>
<br />
<br />

<p>Atraia novos clientes de forma garantida</p>
<br />
<p>Resultados imediatos e mensur&aacute;veis</p>
<br />
<p>Desembolso zero</p>
<br />
<p>Visibilidade para uma audi&ecirc;ncia qualificada de milh&otilde;es
de pessoas</p>
<br />
<p>Ferramenta de marketing extremamente eficiente e livre de risco</p>
<br /><br /><br />

<p><strong>Preencha o formulário abaixo corretamente assim que recebermos entraremos em contato.</strong></p>

<form name="contactForm" id="contactForm" method="post" class="parceiroForm">

	<fieldset class="partners">
		<h5>Dados Gerais:</h5>
		<ol>
			<li><label for="name">Nome:</label> <input type="text" name="nome" id="nome"></li>
			<li><label for="company">Empresa:</label> <input type="text" name="empresa" id="empresa"></li>
			<li><label for="surname">Sobrenome:</label> <input type="text" name="sobrenome" id="sobrenome"></li>
			<li><label for="email">Email:</label> <input type="text" name="email" id="mail-form"></li>
			<li class="clear_all"></li>
		</ol>
		<h5>Dados do seu negócio:</h5>
		<ol>
			<li><label for="category">Categoria:</label><input type="text" name="categoria" id="categoria"></li>
			<li><label for="telephone">Telefone:</label><input type="text" name="telefone" id="telefone" class="Telefone" maxlength="15"></li>
			<li><label for="site">Site:</label><input type="text" name="site" id="site"></li>
			<li><label for="address">Endereço:</label><input type="text" name="endereco" id="endereco"></li>
			<li><label for="state">Estado:</label>
					<select name="estado" id="estado">
					<option value="Acre">Acre</option>
					<option value="Alagoas">Alagoas</option>
					<option value="Amapá">Amapá</option>
					<option value="Amazonas">Amazonas</option>
					<option value="Bahia">Bahia</option>
					<option value="Ceará">Ceará</option>
					<option value="Distrito Federal">Distrito Federal</option>
					<option value="Espírito Santo">Espírito Santo</option>
					<option value="Goiás">Goiás</option>
					<option value="Maranhão">Maranhão</option>
					<option value="Mato Grosso">Mato Grosso</option>
					<option value="Mato Grosso do Sul">Mato Grosso do Sul</option>
					<option value="Minas Gerais">Minas Gerais</option>
					<option value="Pará">Pará</option>
					<option value="Paraíba">Paraíba</option>
					<option value="Paraná">Paraná</option>
					<option value="Pernambuco">Pernambuco</option>
					<option value="Piauí">Piauí</option>
					<option value="Rio de Janeiro">Rio de Janeiro</option>
					<option value="Rio Grande do Norte">Rio Grande do Norte</option>
					<option value="Rio Grande do Sul">Rio Grande do Sul</option>
					<option value="Rondônia">Rondônia</option>
					<option value="Santa Catarina">Santa Catarina</option>
					<option value="Roraima">Roraima</option>
					<option value="São Paulo">São Paulo</option>
					<option value="Sergipe">Sergipe</option>
					<option value="Tocantins">Tocantins</option>
				</select>
			</li>
			<li>
				<label for="city">Cidade:</label><input type="text" name="cidade" id="cidade">
			</li>
			<li>
				<label for="neighborhood">Bairro:</label><input type="text" name="bairro" id="bairro">
			</li>
			<li>
				<label for="cep">CEP:</label><input type="text" name="cep" id="cep" class="CEP" maxlength="9">
			</li>
			<li class="clear_all"></li>
		</ol>
		
		<h5>Conte um pouco sobre seu negócio:</h5><br/>
		
		<textarea name="msg" id="msg"></textarea>
		<div class="clear_all"></div>
		<div class="txtCenter">
		
			<br/>
		
			<button class="Enviar ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" type="submit" id="Logar" name="Logar" role="button" aria-disabled="false">
				<span class="ui-button-text">Clique aqui para enviar seus dados</span>
			</button>
		
		</div>
	</fieldset>
</form>

</div>
