<div id="page-title"><?php echo $this->content['page_title']; ?></div>

<table class="DataTable" id="usuarios-table">
	<thead>
		<tr>
			<th class="item item-nome" width="50%">Nome</th>
			<th class="item item-email" width="70">E-mail</th>
			<th class="item item-credito" width="70">Cr&eacute;dito</th>
			<th class="item item-cidade" width="70">Cidade</th>
		</tr>
	</thead>
	<tbody>
	<?php
		foreach ( $this->dados as $value ){
	?>
		<tr class="item item">
	<?php
			foreach($value as $k => $v){
					echo '<td class="data">' . $v . '</td>';
			}
	?>
		</tr>	
	<?php
		}
	?>

</tbody>
</table>